# bencmark name and version
benchmark_name: CIS Red Hat Enterprise Linux 7 Benchmark v3.0.1

# AIDE section
rhel7cis_aide_cron:
  cron_user: root
  cron_file: /etc/crontab
  aide_job: '/usr/sbin/aide --check'
  aide_minute: 0
  aide_hour: 5
  aide_day: '*'
  aide_month: '*'
  aide_weekday: '*'