# This playbook apply hardening for Red Hat Enterprise Linux 7
# according to CIS Red Hat Enterprise Linux 7 Benchmark
# version 3.0.1 (09-21-2020)
# https://www.cisecurity.org/benchmark/red_hat_linux/
---
- name: Hardening Red Hat Enterprise Linux 7
  hosts: all
  become: yes

  tasks:
    - name: Check if the host is reachable
      ping:
      delegate_to: localhost
      vars:
        ansible_become: no
      register: ping_status
      tags:
        - always

    - name: Group reachable hosts
      group_by: key=reachable
      when: ping_status is success
      tags:
        - always
    
    - name: Apply rules from section 1. Initial Setup
      import_tasks: 1_initial_setup.yaml
      when:
        - ansible_distribution|lower == 'redhat'
        - ansible_distribution_major_version is version_compare('7', '==')
  
  handlers:
    - name: systemd restart tmp.mount
      systemd:
        name: tmp.mount
        daemon_reload: yes
        enabled: yes
        masked: no
        state: reloaded

    # - name: generate new grub config
    #   shell: grub2-mkconfig -o "{{ grub_cfg.stat.lnk_source }}"
    
    - name: start coredump service
      service:
        name: coredump
        state: started
        enabled: yes

